version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "lolwnerawsclient"
        BUILD_ENV: "prod"
phases:
    install:
        runtime-versions:
          nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --env=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive --acl public-read
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
